name: ğŸš€ Deploy Implementation Guide Site Preview on Netlify

on:
  pull_request:
    types: [opened, reopened, edited, synchronize] 

jobs:
  publish:
    name: ğŸ“ Publish Implementation Guide
    runs-on: ubuntu-18.04
    steps:
      - name: ğŸ‘©â€ğŸ’» Checkout code
        uses: actions/checkout@v3
         
      - name: ğŸ›  Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: ğŸ›  Set up Jekyll
        run: |
          sudo apt-get update
          sudo apt-get -y install ruby-full build-essential zlib1g-dev
          sudo gem install jekyll bundler

      - name: ğŸ›  Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12 

      - name: ğŸ›  Install SUSHI and add FSH definitions
        run: |
          npm install -g fsh-sushi
          sushi .

      - name: â¬†ï¸ Update IG publisher
        run: |
          sudo apt-get -y install iputils-ping
          chmod +x ./_updatePublisher.sh
          ./_updatePublisher.sh -y

      - name: ğŸš¦ Validate IG
        run: |
          chmod +x ./_genonce.sh
          ./_genonce.sh

      - name: ğŸš€ Deploy IG to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './output'
          deploy-message: "ğŸš€ Deploy from GitHub Actions"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias: deploy-preview-${{ github.event.number }}
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
